// ===================================================================
// Static catalog of IELTS listening tests.
//   ids   1..88   — original set (hand-maintained below).
//   ids  89..161  — "虾滑VIP" set, generated in the VIP block by
//                   scripts/10-build-vip-tests.ps1 (app_id = 88 + source id).
// frequency: 'high' = 高频, 'sub' = 次高频, 'low' = 非高频.
// ===================================================================
window.TEST_CATALOG = [
  { id: 1,  section: 'P1', frequency: 'high',  title: 'Asia-Pacific Tours Activity Holidays' },
  { id: 2,  section: 'P4', frequency: 'high',  title: 'Human Memory' },
  { id: 3,  section: 'P2', frequency: 'high',  title: 'Shampoo Marketing Project' },
  { id: 4,  section: 'P3', frequency: 'low',   title: 'Handwriting' },
  { id: 5,  section: 'P3', frequency: 'low',   title: 'Using scientific techniques for art' },
  { id: 6,  section: 'P4', frequency: 'high',  title: 'Canadian Maple Syrup' },
  { id: 7,  section: 'P1', frequency: 'low',   title: 'Notes on A Part time Society' },
  { id: 8,  section: 'P4', frequency: 'high',  title: 'Natural Rubber Production' },
  { id: 9,  section: 'P3', frequency: 'low',   title: 'Research on Work Absence' },
  { id: 10, section: 'P2', frequency: 'high',  title: 'Driving License' },
  { id: 11, section: 'P2', frequency: 'low',   title: 'Toy Factory' },
  { id: 12, section: 'P4', frequency: 'low',   title: 'Graphical Symbol' },
  { id: 13, section: 'P3', frequency: 'high',  title: 'The Moa' },
  { id: 14, section: 'P4', frequency: 'low',   title: 'Scottish Case Study' },
  { id: 15, section: 'P1', frequency: 'low',   title: 'Holiday Accommodation Foxton Bay' },
  { id: 16, section: 'P2', frequency: 'high',  title: 'Information for Fire Wardens' },
  { id: 17, section: 'P1', frequency: 'high',  title: 'Birthday Party Arrangement' },
  { id: 18, section: 'P4', frequency: 'high',  title: 'Reintroducing the Beaver Population to Britain' },
  { id: 19, section: 'P3', frequency: 'low',   title: 'Climate Change and Allergies' },
  { id: 20, section: 'P4', frequency: 'low',   title: 'Ancient cave art symbols' },
  { id: 21, section: 'P4', frequency: 'low',   title: 'The Vikings' },
  { id: 22, section: 'P1', frequency: 'low',   title: 'Poppy Reserve' },
  { id: 23, section: 'P2', frequency: 'low',   title: 'Stanley Island' },
  { id: 24, section: 'P4', frequency: 'high',  title: 'African Clawed Frog' },
  { id: 25, section: 'P4', frequency: 'low',   title: 'Office Design 2' },
  { id: 26, section: 'P3', frequency: 'high',  title: 'Foot Injuries' },
  { id: 27, section: 'P3', frequency: 'high',  title: 'Mosquito Net' },
  { id: 28, section: 'P1', frequency: 'low',   title: 'Conforming An Apartment' },
  { id: 29, section: 'P2', frequency: 'high',  title: 'Mitchelstown Choir' },
  { id: 30, section: 'P4', frequency: 'high',  title: 'Dolphin Intelligence' },
  { id: 31, section: 'P4', frequency: 'low',   title: 'Red King Crab' },
  { id: 32, section: 'P1', frequency: 'high',  title: 'Washing Machine Warranty' },
  { id: 33, section: 'P4', frequency: 'high',  title: 'Calotype photography' },
  { id: 34, section: 'P1', frequency: 'high',  title: 'Wedding arrangements' },
  { id: 35, section: 'P4', frequency: 'low',   title: 'Plastics exhibition' },
  { id: 36, section: 'P2', frequency: 'low',   title: 'Eye Saver Charity' },
  { id: 37, section: 'P3', frequency: 'low',   title: "Farmers' attitudes" },
  { id: 38, section: 'P4', frequency: 'low',   title: 'Nanotechnology and Its Applications' },
  { id: 39, section: 'P3', frequency: 'high',  title: 'Buildings made of plastic' },
  { id: 40, section: 'P2', frequency: 'high',  title: 'International Week Celebration' },
  { id: 41, section: 'P1', frequency: 'high',  title: 'Enquiries on Hot Air Balloon Trip' },
  { id: 42, section: 'P1', frequency: 'high',  title: 'Upper Provence folk festival' },
  { id: 43, section: 'P2', frequency: 'low',   title: 'Muna Island' },
  { id: 44, section: 'P4', frequency: 'low',   title: 'Elephant research' },
  { id: 45, section: 'P4', frequency: 'high',  title: 'Insects as a food source' },
  { id: 46, section: 'P3', frequency: 'low',   title: 'Product Marketing on Gender' },
  { id: 47, section: 'P2', frequency: 'low',   title: 'Working for Johnson Jones' },
  { id: 48, section: 'P3', frequency: 'high',  title: 'Maori Carving' },
  { id: 49, section: 'P1', frequency: 'low',   title: 'Ranook Hotel' },
  { id: 50, section: 'P1', frequency: 'high',  title: 'Second-hand Cars' },
  { id: 51, section: 'P2', frequency: 'low',   title: 'Spring Festival' },
  { id: 52, section: 'P4', frequency: 'low',   title: 'Underwater Archaeological Sites' },
  { id: 53, section: 'P4', frequency: 'high',  title: 'Early gold mining in the Otago region' },
  { id: 54, section: 'P3', frequency: 'low',   title: 'Chumbe Nature Reserve' },
  { id: 55, section: 'P1', frequency: 'high',  title: 'Swimming Lessons' },
  { id: 56, section: 'P4', frequency: 'low',   title: 'Boar and Red Deer' },
  { id: 57, section: 'P2', frequency: 'low',   title: 'Davison Wildlife Park' },
  { id: 58, section: 'P3', frequency: 'low',   title: 'Peer Assessment' },
  { id: 59, section: 'P4', frequency: 'low',   title: 'Transhumance' },
  { id: 60, section: 'P3', frequency: 'low',   title: 'Stone Point' },
  { id: 61, section: 'P1', frequency: 'low',   title: 'Holiday on Jackson Island' },
  { id: 62, section: 'P3', frequency: 'low',   title: 'Company Analysis' },
  { id: 63, section: 'P4', frequency: 'high',  title: 'The Antikythera mechanism' },
  { id: 64, section: 'P1', frequency: 'high',  title: 'Temporary Patient Record Form' },
  { id: 65, section: 'P4', frequency: 'high',  title: 'Life on the International Space Station' },
  { id: 66, section: 'P3', frequency: 'high',  title: 'PSWs' },
  { id: 67, section: 'P4', frequency: 'low',   title: 'The Evolution and Cultivation of Vegetables' },
  { id: 68, section: 'P1', frequency: 'high',  title: 'Bicycle Rental Form' },
  { id: 69, section: 'P4', frequency: 'high',  title: 'Crocodile Study' },
  { id: 70, section: 'P2', frequency: 'high',  title: 'Museum Tour' },
  { id: 71, section: 'P1', frequency: 'low',   title: 'Job Inquiry' },
  { id: 72, section: 'P1', frequency: 'low',   title: 'Film club' },
  { id: 73, section: 'P2', frequency: 'high',  title: 'Gisborne' },
  { id: 74, section: 'P4', frequency: 'high',  title: 'The Mangrove' },
  { id: 75, section: 'P3', frequency: 'high',  title: 'Pacific Tapa Cloth' },
  { id: 76, section: 'P4', frequency: 'low',   title: 'Impact of cars in Australia' },
  { id: 77, section: 'P1', frequency: 'low',   title: 'Rented Properties Information About a House' },
  { id: 78, section: 'P4', frequency: 'low',   title: 'History of Music in Britain' },
  { id: 79, section: 'P3', frequency: 'high',  title: 'Value Survey on House Prices' },
  { id: 80, section: 'P1', frequency: 'high',  title: 'Driver Support' },
  { id: 81, section: 'P3', frequency: 'high',  title: 'Internship Options' },
  { id: 82, section: 'P3', frequency: 'high',  title: 'Organising a debate' },
  { id: 83, section: 'P1', frequency: 'high',  title: 'Weekend travel break in Velleya' },
  { id: 84, section: 'P4', frequency: 'high',  title: 'Ingmar Bergman: Film Director' },
  { id: 85, section: 'P3', frequency: 'high',  title: 'Outdoor Activities' },
  { id: 86, section: 'P3', frequency: 'high',  title: 'Dolphin Presentation' },
  { id: 87, section: 'P4', frequency: 'high',  title: 'Bird Surveying Techniques' },
  { id: 88, section: 'P1', frequency: 'low',   title: 'Office Rental' },
  // ==== VIP-LISTENING BEGIN (generated by scripts/10-build-vip-tests.ps1 — do not edit by hand) ====
  { id:   89, section: 'P2', frequency: 'sub'  , title: 'Plan of the Gym' },
  { id:   90, section: 'P4', frequency: 'low'  , title: 'Heat Pump Technology (9.27纸笔)' },
  { id:   91, section: 'P2', frequency: 'sub'  , title: 'The Elmsden Way' },
  { id:   92, section: 'P2', frequency: 'low'  , title: 'Rivermead School' },
  { id:   93, section: 'P4', frequency: 'low'  , title: 'Children Humor' },
  { id:   94, section: 'P3', frequency: 'low'  , title: 'Biogas Plant' },
  { id:   95, section: 'P4', frequency: 'high' , title: 'Company Outsourcing' },
  { id:   96, section: 'P2', frequency: 'low'  , title: 'Plan of Community Center' },
  { id:   97, section: 'P3', frequency: 'low'  , title: 'Treadle irrigation pump (only diagram)' },
  { id:   98, section: 'P4', frequency: 'high' , title: 'The preservation of organisms and fossils' },
  { id:   99, section: 'P4', frequency: 'sub'  , title: 'A.U.V.' },
  { id:  100, section: 'P4', frequency: 'sub'  , title: 'Jatropha- a new biofuel' },
  { id:  101, section: 'P4', frequency: 'high' , title: 'History of time-measurement' },
  { id:  102, section: 'P1', frequency: 'low'  , title: 'Notes on island hotel' },
  { id:  103, section: 'P3', frequency: 'low'  , title: 'Geography Lessons' },
  { id:  104, section: 'P2', frequency: 'low'  , title: 'Fitchton Railway Station' },
  { id:  105, section: 'P4', frequency: 'high' , title: 'Fish Farming' },
  { id:  106, section: 'P2', frequency: 'high' , title: 'Barton House' },
  { id:  107, section: 'P2', frequency: 'low'  , title: 'Hobson Park' },
  { id:  108, section: 'P3', frequency: 'sub'  , title: 'Oral History' },
  { id:  109, section: 'P2', frequency: 'high' , title: 'Map of Melbourne Zoo' },
  { id:  110, section: 'P2', frequency: 'high' , title: 'Bridge to Brisbane Fun Run' },
  { id:  111, section: 'P2', frequency: 'low'  , title: 'Red Hill Suburb' },
  { id:  112, section: 'P4', frequency: 'sub'  , title: 'Gamification' },
  { id:  113, section: 'P3', frequency: 'sub'  , title: 'Subject of Experiments' },
  { id:  114, section: 'P2', frequency: 'low'  , title: 'Plan of Richlands Station' },
  { id:  115, section: 'P3', frequency: 'low'  , title: 'Effect of Walking on Creativity' },
  { id:  116, section: 'P3', frequency: 'low'  , title: 'Nursing Courses' },
  { id:  117, section: 'P4', frequency: 'low'  , title: 'Saving the juniper plant' },
  { id:  118, section: 'P4', frequency: 'low'  , title: 'Mathematics' },
  { id:  119, section: 'P3', frequency: 'low'  , title: 'Education House' },
  { id:  120, section: 'P4', frequency: 'sub'  , title: 'A museum in Japan' },
  { id:  121, section: 'P1', frequency: 'sub'  , title: 'Southwest Cycle Path' },
  { id:  122, section: 'P3', frequency: 'sub'  , title: 'Eyewitness Reliability' },
  { id:  123, section: 'P2', frequency: 'low'  , title: 'Map of Hospital' },
  { id:  124, section: 'P2', frequency: 'high' , title: 'Map of Ocean Edge Hotel' },
  { id:  125, section: 'P2', frequency: 'low'  , title: 'Becoming a millionaire' },
  { id:  126, section: 'P3', frequency: 'low'  , title: 'Music in Restaurants' },
  { id:  127, section: 'P2', frequency: 'low'  , title: 'Basement of Museum' },
  { id:  128, section: 'P4', frequency: 'sub'  , title: 'Sea Lion Tracking Study' },
  { id:  129, section: 'P2', frequency: 'high' , title: 'Map of Accommodation Options' },
  { id:  130, section: 'P2', frequency: 'sub'  , title: 'Map of Biblio Stack' },
  { id:  131, section: 'P2', frequency: 'low'  , title: 'Driving Lessons' },
  { id:  132, section: 'P3', frequency: 'sub'  , title: 'Food Waste' },
  { id:  133, section: 'P1', frequency: 'high' , title: 'Western train incidence report' },
  { id:  134, section: 'P3', frequency: 'high' , title: 'Trademark' },
  { id:  135, section: 'P4', frequency: 'sub'  , title: 'The Early History of Salt' },
  { id:  136, section: 'P2', frequency: 'low'  , title: 'Plan of Home Improvement Store' },
  { id:  137, section: 'P4', frequency: 'high' , title: 'Architecture in New Zealand in 1960s' },
  { id:  138, section: 'P3', frequency: 'low'  , title: 'Professor Smith' },
  { id:  139, section: 'P2', frequency: 'high' , title: 'Map of Different Sites' },
  { id:  140, section: 'P2', frequency: 'low'  , title: 'Home Features and Buying Advice' },
  { id:  141, section: 'P2', frequency: 'high' , title: 'Waste sorting' },
  { id:  142, section: 'P2', frequency: 'low'  , title: 'Plan of Silverton Villa' },
  { id:  143, section: 'P3', frequency: 'low'  , title: 'Group Project' },
  { id:  144, section: 'P4', frequency: 'low'  , title: 'British textile industry' },
  { id:  145, section: 'P2', frequency: 'sub'  , title: 'Cooking School' },
  { id:  146, section: 'P4', frequency: 'sub'  , title: 'History of Bags and Purses' },
  { id:  147, section: 'P2', frequency: 'high' , title: 'The Bike Renting Centre' },
  { id:  148, section: 'P2', frequency: 'low'  , title: 'Plan of SPA (only map)' },
  { id:  149, section: 'P4', frequency: 'sub'  , title: 'Digital Technology' },
  { id:  150, section: 'P3', frequency: 'high' , title: 'Presentation on African Art' },
  { id:  151, section: 'P2', frequency: 'low'  , title: 'Plan of Hollies Supermarket' },
  { id:  152, section: 'P4', frequency: 'high' , title: 'A Survey on Improving Hospitals' },
  { id:  153, section: 'P3', frequency: 'sub'  , title: 'Fashion project on jeans' },
  { id:  154, section: 'P2', frequency: 'high' , title: 'Volunteers at Clifton Bird Park' },
  { id:  155, section: 'P4', frequency: 'sub'  , title: 'Early Migration to America' },
  { id:  156, section: 'P3', frequency: 'low'  , title: 'Renewable Energy' },
  { id:  157, section: 'P3', frequency: 'high' , title: 'Mona\'s Presentation' },
  { id:  158, section: 'P2', frequency: 'high' , title: 'Tourism in the Mining Community' },
  { id:  159, section: 'P2', frequency: 'sub'  , title: 'Outdoor Education Center' },
  { id:  160, section: 'P4', frequency: 'high' , title: 'Monarch Butterflies' },
  { id:  161, section: 'P1', frequency: 'high' , title: 'Yoga Course' },
  { id:  162, section: 'P2', frequency: 'sub'  , title: 'Connections Scheme' },
  { id:  163, section: 'P4', frequency: 'sub'  , title: 'White-lipped Grove Snail' },
  { id:  164, section: 'P2', frequency: 'low'  , title: 'Rosedale Library' },
  { id:  165, section: 'P4', frequency: 'high' , title: 'Perfume Ornaments' },
  { id:  166, section: 'P3', frequency: 'high' , title: 'Intern work in a hotel' },
  { id:  167, section: 'P2', frequency: 'sub'  , title: 'Transportation Mode' },
  { id:  168, section: 'P4', frequency: 'high' , title: 'Comparison of Teaching Methods of Chinese and Scottish Teachers' },
  { id:  169, section: 'P4', frequency: 'sub'  , title: 'Development and use of plastics' },
  { id:  170, section: 'P3', frequency: 'low'  , title: 'Roof Garden Project' },
  { id:  171, section: 'P3', frequency: 'high' , title: 'Bicycle Theft Report' },
  { id:  172, section: 'P4', frequency: 'high' , title: 'The Invasion of Plants' },
  { id:  173, section: 'P2', frequency: 'low'  , title: 'Cocoa Beans' },
  { id:  174, section: 'P2', frequency: 'sub'  , title: 'IWI Island in New Zealand' },
  { id:  175, section: 'P3', frequency: 'high' , title: 'Voice Coaching Workshop' },
  { id:  176, section: 'P1', frequency: 'low'  , title: 'Drama Classes' },
  { id:  177, section: 'P3', frequency: 'sub'  , title: 'Battery-powered Motorbikes' },
  { id:  178, section: 'P4', frequency: 'high' , title: 'History of Bikes' }
  // ==== VIP-LISTENING END ====
  // ==== NEW-STANDARD BEGIN (generated by scripts/13-build-new-standard.ps1 — do not edit by hand) ====
  ,{ id:  179, section: 'P1', frequency: 'sub'  , title: 'Working in a summer camp in the USA' }
  ,{ id:  180, section: 'P2', frequency: 'sub'  , title: 'MUFS' }
  ,{ id:  181, section: 'P1', frequency: 'sub'  , title: 'Getting a job with an airline' }
  ,{ id:  182, section: 'P2', frequency: 'sub'  , title: 'Pine Garden' }
  ,{ id:  183, section: 'P2', frequency: 'low'  , title: 'Charity Art Sale' }
  ,{ id:  184, section: 'P1', frequency: 'high' , title: 'Horseback-trip' }
  ,{ id:  185, section: 'P1', frequency: 'low'  , title: 'Fruit-picking part-time job' }
  ,{ id:  186, section: 'P2', frequency: 'low'  , title: 'Saving Energy' }
  ,{ id:  187, section: 'P1', frequency: 'sub'  , title: 'International Club' }
  ,{ id:  188, section: 'P2', frequency: 'low'  , title: 'Riding for the Disabled (RDA)' }
  ,{ id:  189, section: 'P1', frequency: 'low'  , title: 'Lifeguard Application' }
  ,{ id:  191, section: 'P3', frequency: 'sub'  , title: 'Willows Studies' }
  ,{ id:  192, section: 'P2', frequency: 'sub'  , title: 'Walking Holiday' }
  ,{ id:  193, section: 'P1', frequency: 'high' , title: 'Student Accommodation' }
  ,{ id:  194, section: 'P2', frequency: 'high' , title: 'Restaurant Reviews' }
  ,{ id:  195, section: 'P1', frequency: 'high' , title: 'Rental Property Application Form' }
  // ==== NEW-STANDARD END ====
];
