// ===================================================================
// Static catalog of all 88 IELTS listening tests.
// id = the leading number from the source filename.
// Generated from the IELTS Listening source folder.
// ===================================================================
window.TEST_CATALOG = [
  { id: 1,  section: 'P1', frequency: 'high',  title: 'Asia-Pacific Tours Activity Holidays' },
  { id: 2,  section: 'P4', frequency: 'high',  title: 'Human Memory' },
  { id: 3,  section: 'P2', frequency: 'high',  title: 'Shampoo Marketing Project' },
  { id: 4,  section: 'P3', frequency: 'low',   title: 'Handwriting' },
  { id: 5,  section: 'P3', frequency: 'low',   title: 'Using scientific techniques for art' },
  { id: 6,  section: 'P4', frequency: 'high',  title: 'Canadian Maple Syrup' },
  { id: 7,  section: 'P1', frequency: 'low',   title: 'Notes on A Part time Society' },
  { id: 8,  section: 'P4', frequency: 'high',  title: 'Natural Rubber Production' },
  { id: 9,  section: 'P3', frequency: 'low',   title: 'Research on Work Absence' },
  { id: 10, section: 'P2', frequency: 'high',  title: 'Driving License' },
  { id: 11, section: 'P2', frequency: 'low',   title: 'Toy Factory' },
  { id: 12, section: 'P4', frequency: 'low',   title: 'Graphical Symbol' },
  { id: 13, section: 'P3', frequency: 'high',  title: 'The Moa' },
  { id: 14, section: 'P4', frequency: 'low',   title: 'Scottish Case Study' },
  { id: 15, section: 'P1', frequency: 'low',   title: 'Holiday Accommodation Foxton Bay' },
  { id: 16, section: 'P2', frequency: 'high',  title: 'Information for Fire Wardens' },
  { id: 17, section: 'P1', frequency: 'high',  title: 'Birthday Party Arrangement' },
  { id: 18, section: 'P4', frequency: 'high',  title: 'Reintroducing the Beaver Population to Britain' },
  { id: 19, section: 'P3', frequency: 'low',   title: 'Climate Change and Allergies' },
  { id: 20, section: 'P4', frequency: 'low',   title: 'Ancient cave art symbols' },
  { id: 21, section: 'P4', frequency: 'low',   title: 'The Vikings' },
  { id: 22, section: 'P1', frequency: 'low',   title: 'Poppy Reserve' },
  { id: 23, section: 'P2', frequency: 'low',   title: 'Stanley Island' },
  { id: 24, section: 'P4', frequency: 'high',  title: 'African Clawed Frog' },
  { id: 25, section: 'P4', frequency: 'low',   title: 'Office Design 2' },
  { id: 26, section: 'P3', frequency: 'high',  title: 'Foot Injuries' },
  { id: 27, section: 'P3', frequency: 'high',  title: 'Mosquito Net' },
  { id: 28, section: 'P1', frequency: 'low',   title: 'Conforming An Apartment' },
  { id: 29, section: 'P2', frequency: 'high',  title: 'Mitchelstown Choir' },
  { id: 30, section: 'P4', frequency: 'high',  title: 'Dolphin Intelligence' },
  { id: 31, section: 'P4', frequency: 'low',   title: 'Red King Crab' },
  { id: 32, section: 'P1', frequency: 'high',  title: 'Washing Machine Warranty' },
  { id: 33, section: 'P4', frequency: 'high',  title: 'Calotype photography' },
  { id: 34, section: 'P1', frequency: 'high',  title: 'Wedding arrangements' },
  { id: 35, section: 'P4', frequency: 'low',   title: 'Plastics exhibition' },
  { id: 36, section: 'P2', frequency: 'low',   title: 'Eye Saver Charity' },
  { id: 37, section: 'P3', frequency: 'low',   title: "Farmers' attitudes" },
  { id: 38, section: 'P4', frequency: 'low',   title: 'Nanotechnology and Its Applications' },
  { id: 39, section: 'P3', frequency: 'high',  title: 'Buildings made of plastic' },
  { id: 40, section: 'P2', frequency: 'high',  title: 'International Week Celebration' },
  { id: 41, section: 'P1', frequency: 'high',  title: 'Enquiries on Hot Air Balloon Trip' },
  { id: 42, section: 'P1', frequency: 'high',  title: 'Upper Provence folk festival' },
  { id: 43, section: 'P2', frequency: 'low',   title: 'Muna Island' },
  { id: 44, section: 'P4', frequency: 'low',   title: 'Elephant research' },
  { id: 45, section: 'P4', frequency: 'high',  title: 'Insects as a food source' },
  { id: 46, section: 'P3', frequency: 'low',   title: 'Product Marketing on Gender' },
  { id: 47, section: 'P2', frequency: 'low',   title: 'Working for Johnson Jones' },
  { id: 48, section: 'P3', frequency: 'high',  title: 'Maori Carving' },
  { id: 49, section: 'P1', frequency: 'low',   title: 'Ranook Hotel' },
  { id: 50, section: 'P1', frequency: 'high',  title: 'Second-hand Cars' },
  { id: 51, section: 'P2', frequency: 'low',   title: 'Spring Festival' },
  { id: 52, section: 'P4', frequency: 'low',   title: 'Underwater Archaeological Sites' },
  { id: 53, section: 'P4', frequency: 'high',  title: 'Early gold mining in the Otago region' },
  { id: 54, section: 'P3', frequency: 'low',   title: 'Chumbe Nature Reserve' },
  { id: 55, section: 'P1', frequency: 'high',  title: 'Swimming Lessons' },
  { id: 56, section: 'P4', frequency: 'low',   title: 'Boar and Red Deer' },
  { id: 57, section: 'P2', frequency: 'low',   title: 'Davison Wildlife Park' },
  { id: 58, section: 'P3', frequency: 'low',   title: 'Peer Assessment' },
  { id: 59, section: 'P4', frequency: 'low',   title: 'Transhumance' },
  { id: 60, section: 'P3', frequency: 'low',   title: 'Stone Point' },
  { id: 61, section: 'P1', frequency: 'low',   title: 'Holiday on Jackson Island' },
  { id: 62, section: 'P3', frequency: 'low',   title: 'Company Analysis' },
  { id: 63, section: 'P4', frequency: 'high',  title: 'The Antikythera mechanism' },
  { id: 64, section: 'P1', frequency: 'high',  title: 'Temporary Patient Record Form' },
  { id: 65, section: 'P4', frequency: 'high',  title: 'Life on the International Space Station' },
  { id: 66, section: 'P3', frequency: 'high',  title: 'PSWs' },
  { id: 67, section: 'P4', frequency: 'low',   title: 'The Evolution and Cultivation of Vegetables' },
  { id: 68, section: 'P1', frequency: 'high',  title: 'Bicycle Rental Form' },
  { id: 69, section: 'P4', frequency: 'high',  title: 'Crocodile Study' },
  { id: 70, section: 'P2', frequency: 'high',  title: 'Museum Tour' },
  { id: 71, section: 'P1', frequency: 'low',   title: 'Job Inquiry' },
  { id: 72, section: 'P1', frequency: 'low',   title: 'Film club' },
  { id: 73, section: 'P2', frequency: 'high',  title: 'Gisborne' },
  { id: 74, section: 'P4', frequency: 'high',  title: 'The Mangrove' },
  { id: 75, section: 'P3', frequency: 'high',  title: 'Pacific Tapa Cloth' },
  { id: 76, section: 'P4', frequency: 'low',   title: 'Impact of cars in Australia' },
  { id: 77, section: 'P1', frequency: 'low',   title: 'Rented Properties Information About a House' },
  { id: 78, section: 'P4', frequency: 'low',   title: 'History of Music in Britain' },
  { id: 79, section: 'P3', frequency: 'high',  title: 'Value Survey on House Prices' },
  { id: 80, section: 'P1', frequency: 'high',  title: 'Driver Support' },
  { id: 81, section: 'P3', frequency: 'high',  title: 'Internship Options' },
  { id: 82, section: 'P3', frequency: 'high',  title: 'Organising a debate' },
  { id: 83, section: 'P1', frequency: 'high',  title: 'Weekend travel break in Velleya' },
  { id: 84, section: 'P4', frequency: 'high',  title: 'Ingmar Bergman: Film Director' },
  { id: 85, section: 'P3', frequency: 'high',  title: 'Outdoor Activities' },
  { id: 86, section: 'P3', frequency: 'high',  title: 'Dolphin Presentation' },
  { id: 87, section: 'P4', frequency: 'high',  title: 'Bird Surveying Techniques' },
  { id: 88, section: 'P1', frequency: 'low',   title: 'Office Rental' }
];
